const DEFAULT_CLIENT_IMAGE = "BRAND_MONKEY_LOGO_CLIENT.jpeg";
const DEFAULT_EMPLOYEE_IMAGE = "BRAND_MONKEY_LOGO_EMPLOYEE.jpeg";

module.exports = {
	DEFAULT_CLIENT_IMAGE,
	DEFAULT_EMPLOYEE_IMAGE,
};


